export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_SKILLS_SUCCESS = 'LOAD_SKILLS_SUCCESS';
export const CREATE_SKILL_SUCCESS = 'CREATE_SKILL_SUCCESS';
export const UPDATE_SKILL_SUCCESS = 'UPDATE_SKILL_SUCCESS';

export const LOAD_USERS_SUCCESS = 'LOAD_USERS_SUCCESS';
